# Generated by Django 2.1.5 on 2019-02-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='abilities',
            field=models.CharField(max_length=255),
        ),
    ]
