# Generated by Django 2.1.5 on 2019-02-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_app', '0002_auto_20190202_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
