# Generated by Django 2.1.5 on 2019-02-06 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero_app', '0004_auto_20190206_0358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
