# Generated by Django 2.1.5 on 2019-02-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_app', '0005_auto_20190206_0428'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('score', models.CharField(max_length=255)),
                ('pic', models.CharField(max_length=255)),
            ],
        ),
    ]
