# Generated by Django 2.1.5 on 2019-02-11 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero_app', '0006_githubplayer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubplayer',
            old_name='username',
            new_name='name',
        ),
    ]
